old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        create_report_profitable_algorithms:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.create_report_profitable_algorithms', type: direct }
        create_report_settings_for_profitable_algorithms:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.create_report_settings_for_profitable_algorithms', type: direct }

    consumers:
        create_report_profitable_algorithms:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.create_report_profitable_algorithms', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.create_report_profitable_algorithms' }
            callback:               App\Consumer\CreateReportProfitableAlgorithms\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
        create_report_settings_for_profitable_algorithms:
            connection:             default
            exchange_options: { name: 'old_sound_rabbit_mq.create_report_settings_for_profitable_algorithms', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.create_report_settings_for_profitable_algorithms' }
            callback:               App\Consumer\CreateReportSettingsForProfitableAlgorithms\Consumer
            idle_timeout:           300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout:   1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
